import RNFS from 'react-native-fs';
import Share from 'react-native-share';
import { Database } from '@nozbe/watermelondb';
import { Q } from '@nozbe/watermelondb';
import Patient from '../database/models/Patient';
import Visit from '../database/models/Visit';
import { formatDate, formatTime, formatDuration } from '../utils/dateUtils';
import { formatCurrency } from '../utils/formatUtils';

export interface BillData {
  patient: Patient;
  visits: Visit[];
  fromDate: Date;
  toDate: Date;
  totalCharge: number;
  totalPaid: number;
  balanceDue: number;
  totalMinutes: number;
}

export async function loadBillData(
  patientId: string,
  fromDate: Date,
  toDate: Date,
): Promise<BillData> {
  const { patientsCollection, visitsCollection } = await import('../database');
  const patient = await patientsCollection.find(patientId);
  const visits = await visitsCollection
    .query(
      Q.where('patient_id', patientId),
      Q.where('status', 'completed'),
      Q.where('start_time', Q.gte(fromDate.getTime())),
      Q.where('start_time', Q.lte(toDate.getTime())),
    )
    .fetch();

  const totalCharge = visits.reduce((s, v) => s + v.charge, 0);
  const totalPaid = visits.filter(v => v.isPaid).reduce((s, v) => s + v.charge, 0);
  const balanceDue = totalCharge - totalPaid;
  const totalMinutes = visits.reduce((s, v) => s + (v.durationMin ?? 0), 0);

  return { patient, visits, fromDate, toDate, totalCharge, totalPaid, balanceDue, totalMinutes };
}

export function generateTextBill(data: BillData): string {
  const { patient, visits, fromDate, toDate, totalCharge, totalPaid, balanceDue } = data;
  const line = '════════════════════════════════════════════';
  const divider = '────────────────────────────────────────────';

  let rows = '';
  visits.forEach((v, i) => {
    const date = formatDate(v.startTime, 'short');
    const start = formatTime(v.startTime);
    const end = v.endTime ? formatTime(v.endTime) : '—';
    const dur = v.durationMin ?? 0;
    const num = String(i + 1).padEnd(4);
    const dateStr = date.padEnd(12);
    const startStr = start.padEnd(8);
    const endStr = end.padEnd(8);
    const durStr = String(dur).padEnd(5);
    const amt = formatCurrency(v.charge);
    rows += `${num} ${dateStr} ${startStr} ${endStr} ${durStr} ${amt}\n`;
  });

  return [
    line,
    `         🩺  PhyJio  |  Home Physiotherapy`,
    `                   INVOICE`,
    line,
    `Patient:  ${patient.fullName}`,
    `Age:      ${patient.age} years`,
    `Ailment:  ${patient.ailment}`,
    `Period:   ${formatDate(fromDate, 'short')} – ${formatDate(toDate, 'short')}`,
    divider,
    `No.  Date         Start    End      Min   Amt`,
    divider,
    rows.trimEnd(),
    divider,
    `TOTAL CHARGE:                        ${formatCurrency(totalCharge)}`,
    `Amount Paid:                         ${formatCurrency(totalPaid)}`,
    `BALANCE DUE:                         ${formatCurrency(balanceDue)}`,
    line,
    `  Generated by PhyJio on ${formatDate(new Date(), 'short')}`,
    line,
  ].join('\n');
}

export async function shareTextBill(data: BillData): Promise<void> {
  const text = generateTextBill(data);
  const filename = `PhyJio_Bill_${data.patient.fullName.replace(/\s+/g, '_')}_${Date.now()}.txt`;
  const path = `${RNFS.DocumentDirectoryPath}/${filename}`;
  await RNFS.writeFile(path, text, 'utf8');
  await Share.open({ url: `file://${path}`, type: 'text/plain', filename });
}

export async function markVisitsPaid(visits: Visit[], db: Database): Promise<void> {
  await db.write(async () => {
    const updates = visits
      .filter(v => !v.isPaid)
      .map(v =>
        v.prepareUpdate(record => {
          (record as Visit).isPaid = true;
        }),
      );
    await db.batch(...updates);
  });
}
